grpc:
  name: "scheduler-service"
  host: "0.0.0.0:50051"

redis:
  mode: "standalone" # standalone | cluster 
  hosts:
    - "redis:6379"
  cluster: false
  serve_reads_from_slaves: true
  serve_reads_from_master_and_slaves: true
  min_idle_conns: 10
  idle_timeout: 600000
  pool_size: 75
  read_timeout: 1000
  write_timeout: 1000
  dial_timeout: 500

dynamo:
  region: "us-east-1"
  endpoint: "http://dynamodb:8000"
  table_name: "scheduler-service-table"

kafka:
  brokers:
    - "kafka:9092"
  group_id: "scheduler-consumer"

scheduler:
  total_partitions: 4
  bucket_size_sec: 60

scheduler_worker:
  past_buckets_count: 5
  semaphore_limit: 20
  batch_size: 50
  backoff_ms: 10
  max_backoff_ms: 1000

retry_worker:
  past_buckets_count: 5
  retry_scan_interval_ms: 5000
  retry_batch_size: 50
